apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service-deployment
  labels:
    app: websocket-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
      - name: websocket-service
        image: ingress-lab/websocket-service:latest
        ports:
        - containerPort: 3002
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  selector:
    app: websocket-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP